### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by saeedizadi** [yassersouri/fandak#1]
Cool, 
I also have a framework integrating Sacred for experiment tracking and logging into PyTorch project. Would be happy to collaborate, if interested.

**Comment by yassersouri** [comment]
Hi,
Thanks.

I am mostly interested in a framework for research development. The goal is not that you should be able to train Imagenet in 20 lines of code, but rather to have a framework to develop for multiple months on a deep learning research project and still remain sane and have relatively clean code base!

I am also interested in collaboration. We can also discuss offline if you like.
